[project]
name = "attercop"
version = "0.1.0"

description = "A simple calculator POC for semantic release demo"
authors = [{name = "Your Name", email = "your.email@example.com"}]
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 3 - Alpha",

    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dependencies = [
    "black>=25.1.0",
    "pre-commit>=4.2.0",
    "pyright>=1.1.401",
    "pytest>=8.4.0",
    "ruff>=0.11.13",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "black>=23.0.0",
    "isort>=5.12.0",
    "flake8>=6.0.0",
    "pre-commit>=3.0.0",
]

[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/calculator/_version.py"

[tool.semantic_release]
version_toml = ["pyproject.toml:project.version"]
version_variable = "src/your_package/__init__.py:__version__"
build_command = "pip install build && python -m build"
upload_to_pypi = false
upload_to_release = true
commit_author = "github-actions <github-actions@github.com>"
# Handle first release
tag_format = "v{version}"
major_on_zero = false
allow_zero_version = truev1.0.0

[tool.semantic_release.branches.main]
match = "main"
prerelease = false

[tool.semantic_release.changelog]
template_dir = "templates"
changelog_file = "CHANGELOG.md"

[tool.semantic_release.remote]
name = "origin"
type = "github"

[tool.black]
line-length = 88
target-version = ['py38']

[tool.isort]
profile = "black"
line_length = 88

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_functions = ["test_*"]
