name: Reusable Build Workflow

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: false
        default: 'development'
        type: string
      node-version:
        description: 'Node.js version to use'
        required: false
        default: '18'
        type: string
    outputs:
      build-status:
        description: 'Status of the build'
        value: ${{ jobs.build.outputs.status }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.build-step.outputs.status }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run build
        id: build-step
        run: |
          echo "Building for ${{ inputs.environment }} environment"
          npm run build
          echo "status=success" >> $GITHUB_
